config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  devise_for :users


  scope module: 'users' do
 		get '/users/mypage', to: 'users#mypage', as: 'mypage'
 		get '/users/mypage/info', to: 'users#info', as: 'info'
 		get '/users/mypage/info_edit', to: 'users#edit', as: 'edit'
     resources :users, only: [:show, :update] do
 		  get :confirm, on: :member # 退会確認
       patch :withdrawal, on: :member # 退会処理
 		end
  end

  root to: "homes#top"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :user_state, only: [:create]

  def create
    user = User.find_by(email: params[:user][:email])

    if user && user.valid_password?(params[:user][:password]) && user.is_active
      sign_in user
      redirect_to mypage_path
    else
      flash[:alert] = "ログインできません。アカウントが無効になっているか、パスワードが正しくありません。"
      render 'user/registrations/new'
    end
  end

  protected

  def user_state
    @user = User.find_by(email: params[:user][:email])

    if !@user
      flash[:alert] = "アカウントが見つかりませんでした。"
      redirect_to new_user_registration_path
    elsif !@user.is_active?
      flash[:alert] = "退会済みのアカウントです。"
      redirect_to new_user_registration_path
    end
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/users_controller.rb
class Users::UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:show, :update, :confirm, :withdrawal]

  def mypage #顧客のマイページ
    @user = current_user
  end

  def info #顧客の登録情報画面
    @user = current_user
  end

  def edit #顧客の登録情報編集画面
    @user = current_user
  end

  def update #顧客の登録情報更新
    @user = current_user
    if @user.update(user_params)
      flash[:notice] = '登録情報を更新しました'
      redirect_to info_path
    else
      render 'users_info_edit'
    end
  end

  def confirm #退会確認画面
    is_matching_login_user
    @user = User.find(params[:id])
  end

  def withdrawal  #退会画面
    @user = User.find(params[:id])
    @user.update(is_active: false)

    sign_out @user
    redirect_to root_path, notice: "アカウントが削除されました。"
  end

  private

  def user_params
    params.require(:user).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number, :is_active, :password, :password_confirmation)
  end

  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/user/user_helper.rb
module User::UserHelper
end

app/views/users/users/confirm.html.erb
<div class="container">
  <h5 style="text-align: center;">
    <b>退会</b>
  </h5>

  <div class="row justify-content-center">
    <div class="col-md-10">
      <p>下記の注意事項を確認のうえ、チェックを入れて「退会する」ボタンを押してください</p>

      <div class="withdraw-checked">
        <label>
          <input type="checkbox" name="withdraw_agreement" id="withdraw-agreement">
          退会後、登録内容はできなくなります
        </label>
      </div>

      <div class="withdraw-checked">
        <label>
          <input type="checkbox" name="withdraw_agreement" id="withdraw-agreement">
          既にご注文いただいている商品は、退会後も発送させていただきます
        </label>
      </div>

      <div class="row justify-content-center">
        <div class="col-md-6">
          <%= link_to "退会する", withdrawal_user_path, method: :patch, class: "btn btn-outline-danger btn-block", id: "withdraw-button", disabled: true %>
        </div>
      </div>

      <div class="row justify-content-center">
        <div class="col-md-6">
          <%= link_to "戻る", mypage_path , class: "btn btn-light btn-block" %>
        </div>
      </div>

    </div>
  </div>

</div>

app/views/users/users/edit.html.erb
<div class="container">
<h5 style="text-align: center;"><b>会員情報変更</b></h5>

  <div class="row justify-content-center">
    <div class="col-md-6">

    <%= form_for @user, url: user_path(@user), method: :patch do |f| %>

      <!-- エラーチェック -->
      <% if @user.errors.any? %>
        <%= @user.errors.count %> errors prohibited this obj from being saved:
        <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      <% end %>

      <div class="row form-group">
        <div class="col-md-12">
          <b><%= f.label :'名前（必須)' %></b>
        </div>
        <%= f.text_field :last_name, placeholder: '(例)山田',autofocus: true, class: "col-md-6 example-text" %>
        <%= f.text_field :first_name, placeholder: '(例)太郎',autofocus: true, class: "col-md-6 example-text" %>
      </div>

      <div class="row form-group">
        <div class="col-md-12">
          <b><%= f.label :'カナ（必須）' %></b>
        </div>
        <%= f.text_field :last_name_kana, placeholder: '(例)ヤマダ', autofocus: true, class: "col-md-6" %>
        <%= f.text_field :first_name_kana, placeholder: '(例)タロウ', autofocus: true, class: "col-md-6" %>
      </div>

      <div class="row form-group">
        <b><%= f.label :"郵便番号(ハイフンなし)", class: "col-md-12" %></b>
        <%= f.text_field :postal_code, placeholder: '0123456', autofocus: true, class: "col-md-12" %>
      </div>

      <div class="row form-group">
        <b><%= f.label :住所, class: "col-md-12" %></b>
        <%= f.text_field :address, placeholder: '○○県△△市××町1-2-3' , autofocus: true, class: "col-md-12" %>
      </div>

      <div class="row form-group">
        <b><%= f.label :"電話番号(ハイフンなし)", class: "col-md-12" %></b>
        <%= f.text_field :telephone_number, placeholder: '0123456789', autofocus: true, class: "col-md-12" %>
      </div>

      <div class="row form-group">
        <b><%= f.label :メールアドレス, class: "col-md-12" %></b>
        <%= f.email_field :email, placeholder: 'メールアドレスを入力してください。', autofocus: true, class: "col-md-12" %>
        <p style="color: red;">ログインの際に必要になります。忘れないようにしてください。</p>
      </div>

      <div class="row justify-content-center">
        <div class="col-md-6">
          <%= f.submit "変更する" ,class: "btn btn-dark btn-block" %>
        </div>
      </div>
      
      <div class="row justify-content-center">
        <div class="col-md-6">
          <%= link_to "戻る", mypage_path , class: "btn btn-light btn-block" %>
        </div>
      </div>

    <% end %>
    </div>
  </div>
</div>

app/views/users/users/info.html.erb
<div class="container">
<h5 style="text-align: center;">
  <b>会員登録情報</b>
  <%= link_to edit_path do %>
    <i class="fa-solid fa-user-pen"></i>
  <% end %>
</h5>


  <div class="row justify-content-center">
    <div class="col-md-6">
      <% if @user.present? %>
        <div class="row form-group">
          <div class="col-md-12">
            <b>氏名</b>
          </div>
          <%= @user.last_name %>　<%= @user.first_name %>
        </div>

        <div class="row form-group">
          <div class="col-md-12">
            <b>カナ</b>
          </div>
          <%= @user.last_name_kana %>　<%= @user.first_name_kana %></td>
        </div>

        <div class="row form-group">
          <div class="col-md-12">
            <b>郵便番号</b>
          </div>
          〒<%= @user.postal_code %>
        </div>

        <div class="row form-group">
          <div class="col-md-12">
            <b>住所</b>
          </div>
          <%= @user.address %>
        </div>

        <div class="row form-group">
          <div class="col-md-12">
            <b>電話番号</b>
          </div>
          <%= @user.telephone_number %>
        </div>

        <div class="row form-group">
          <div class="col-md-12">
            <b>メールアドレス</b>
          </div>
          <%= @user.email %>
        </div>

        <div class="row justify-content-center">
          <div class="col-md-6">
            <%= link_to "戻る", mypage_path , class: "btn btn-light btn-block" %>
          </div>
        </div>


      <% end %>

    </div>
  </div>
</div>

app/views/users/users/my_page.html.erb
<div class="container">
<h5 style="text-align: center;"><b>会員登録情報</b></h5>
<%= link_to infomation_path(@user) %>

  <div class="row justify-content-center">
    <div class="col-md-6">
      <% if @user.present? %>
        <div class="row form-group">
          <div class="col-md-12">
            <b>氏名</b>
          </div>
          <%= @user.last_name %>　<%= @user.first_name %>
        </div>

        <div class="row form-group">
          <div class="col-md-12">
            <b>カナ</b>
          </div>
          <%= @user.last_name_kana %>　<%= @user.first_name_kana %></td>
        </div>

        <div class="row form-group">
          <div class="col-md-12">
            <b>郵便番号</b>
          </div>
          〒<%= @user.postal_code %>
        </div>

        <div class="row form-group">
          <div class="col-md-12">
            <b>住所</b>
          </div>
          <%= @user.address %>
        </div>

        <div class="row form-group">
          <div class="col-md-12">
            <b>電話番号</b>
          </div>
          <%= @user.telephone_number %>
        </div>

        <div class="row form-group">
          <div class="col-md-12">
            <b>メールアドレス</b>
          </div>
          <%= @user.email %>
        </div>


      <% end %>

    </div>
  </div>
</div>

app/views/users/users/mypage.html.erb
<div class="container">
  <h5 style="text-align: center;">
    <b>会員登録情報</b>
  </h5>


  <div class="row justify-content-center">
    <div class="col-md-6">
      <ul>

        <li>
          <%= link_to info_path do %>
            会員登録情報の変更
          <% end %>
        </li>

        <li>
          <%= link_to confirm_user_path(@user) do %>
            退会手続き
          <% end %>
        </li>

        <li>

            注文履歴

        </li>

      </ul>
    </div>
  </div>
</div>