config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  devise_for :users


  scope module: 'users' do
 		get '/users/mypage', to: 'users#mypage', as: 'mypage'
 		get '/users/mypage/info', to: 'users#info', as: 'info'
 		get '/users/mypage/info_edit', to: 'users#edit', as: 'edit'
     resources :users, only: [:show, :update] do
 		  get :confirm, on: :member # 退会確認
       patch :withdrawal, on: :member # 退会処理
 		end
  end

  root to: "homes#top"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SHOP</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/1a020bd911.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header>
      <nav class="navbar navbar-expand-lg text-white">
        <div class="container">

          <%= link_to root_path , class: 'logo' do %>
            <%= image_tag('logo.png', size: '120x60') %>
          <% end %>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon">
              <i class="fas fa-bars"></i>
            </span>
          </button>

          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">

              <% if user_signed_in? %><!-- 顧客がログインしている場合のメニュー項目 -->

                <li class="nav-item">
                  <%= link_to mypage_path do %>
                    <i class="fa fa-right-from-bracket"></i> マイページ
                  <% end %>
                </li>

                <li class="nav-item">
                  <%= link_to destroy_user_session_path, method: :delete do %>
                    <i class="fa fa-right-from-bracket"></i> ログアウト
                  <% end %>
                </li>

              <% elsif admin_signed_in? %><!-- 管理者がログインしている場合のメニュー項目 -->



                <li class="nav-item">
                  <p>
                    <i class="fa fa-users"></i> 会員一覧
                  </p>
                </li>

                <li class="nav-item">
                  <%= link_to destroy_user_session_path, method: :delete do %>
                    <i class="fa fa-right-from-bracket"></i> ログアウト
                  <% end %>
                </li>

              <% else %>


                <li class="nav-item">
                  <%= link_to new_user_registration_path do %>
                    <i class="fa fa-arrow-right-to-bracket"></i> 新規登録
                  <% end %>
                </li>

                <li class="nav-item">
                  <%= link_to new_user_session_path do %>
                    <i class="fa fa-right-to-bracket"></i> ログイン
                  <% end %>
                </li>
               <% end %>

            </ul>
          </div>
        </div>
      </nav>
    </header>

    <%= yield %>
  </body>
</html>